[build-system]
requires = ["setuptools >= 64"]
build-backend = "setuptools.build_meta"

# https://docs.astral.sh/ruff/rules/
[tool.ruff.lint.per-file-ignores]
"__init__.py" = ["E402", "F401"]
"**/{tests,docs,tools}/*" = ["E402", "F401"]
